spring:
  application:
    name: srsly
  datasource:
    url: jdbc:postgresql://localhost:5432/<db_name>
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    google:
      genai:
        api-key: <api-key>
    retry:
      max-attempts: 2

security:
  jwt:
    secret-key: <secret-key>
    expiration-time: <expiration-time>



