CREATE SEQUENCE problems_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE tags_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE solutions_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE review_attempts_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE review_problems_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE solved_problems_seq START WITH 1 INCREMENT BY 50;
